/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-08-28 09:58:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Tickets/GestionApp.java;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("Tickets/GestionApp.java");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Administracion del sistema</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"admin.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"plans\">\r\n");
      out.write("    <div class=\"plan\">\r\n");
      out.write("      <h2 class=\"plan-title\">Consultar</h2>\r\n");
      out.write("      <p class=\"plan-price\"><img src=\"https://cutt.ly/8LGRT6D\"> </p>\r\n");
      out.write("      <ul class=\"plan-features\">\r\n");
      out.write("        <li>Incidencias\r\n");
      out.write("       <strong>abiertas por\r\n");
      out.write("        usuarios</strong></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      ");
 gestionApp.buscaTodasLasInciddenciasAbiertas(); 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"plan\">\r\n");
      out.write("      <h2 class=\"plan-title\">Consultar</h2>\r\n");
      out.write("      <p class=\"plan-price\"><img src=\"https://cutt.ly/8LGRT6D\"></p>\r\n");
      out.write("      <ul class=\"plan-features\">\r\n");
      out.write("        <li>Incidencias <strong>cerradas por usuarios</strong></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      ");
 gestionApp.incidenciasCerradasResueltas(); 
      out.write("<\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"plan\">\r\n");
      out.write("      <h2 class=\"plan-title\">Consultar</h2>\r\n");
      out.write("      <p class=\"plan-price\"><img src=\"https://cutt.ly/8LGRT6D\"></p>\r\n");
      out.write("      <ul class=\"plan-features\">\r\n");
      out.write("        <li> <strong>Incidencias por termino</strong> </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      ");
 gestionApp.buscaIncidenciaByTerm(termino); 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <div class=\"plan\">\r\n");
      out.write("      <h2 class=\"plan-title\">Consultar</h2>\r\n");
      out.write("      <p class=\"plan-price\"><img src=\"https://cutt.ly/8LGRT6D\"></p>\r\n");
      out.write("      <ul class=\"plan-features\">\r\n");
      out.write("        <li>Los <strong> tecnicos</strong></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      ");
 gestionApp.getTecnicos();
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     <div class=\"plan\">\r\n");
      out.write("      <h2 class=\"plan-title\">Asignar</h2>\r\n");
      out.write("      <p class=\"plan-price\"><img src=\"https://cutt.ly/8LGRT6D\"></p>\r\n");
      out.write("      <ul class=\"plan-features\">\r\n");
      out.write("        <li>Incidencia <strong> a un tecnico</strong></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      ");
 gestionApp.asignaIncidenciaaTecnico(gestionApp.buscaIncidencia(idIncidencia), gestionApp.buscaTecnico(idTecnico)); 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     <div class=\"plan\">\r\n");
      out.write("      <h2 class=\"plan-title\">Dar de alta</h2>\r\n");
      out.write("      <p class=\"plan-price\"><img src=\"https://cutt.ly/8LGRT6D\"></p>\r\n");
      out.write("      <ul class=\"plan-features\">\r\n");
      out.write("        <li> <strong> A un tecnico</strong></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      ");
registrarmeTécnico();/*String nombre, String apel, String clave, String mail*/
      nombre = cad.nextLine(); apel = cad.nextLine(); clave = cad.nextLine(); mail = cad.nextLine();
      gestionApp.insertaTecnico(nombre, apel, clave, mail);

      //###########log##########
      try {
          BufferedWriter bw = new BufferedWriter(new FileWriter("log.dat"));
          texto += "[Técnico dado de alta" + nombre +" - "+ LocalDate.now() + "]"+"\n";
          bw.write(texto);
          bw.close();
      } catch (IOException e) {
          System.out.println("");
      } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     <div class=\"plan\">\r\n");
      out.write("      <h2 class=\"plan-title\">Borrar</h2>\r\n");
      out.write("      <p class=\"plan-price\"><img src=\"https://cutt.ly/8LGRT6D\"></p>\r\n");
      out.write("      <ul class=\"plan-features\">\r\n");
      out.write("        <li> <strong> A un tecnico</strong></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      ");
 gestionApp.borrarTecnico(id); 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     <div class=\"plan\">\r\n");
      out.write("      <h2 class=\"plan-title\">Consultar</h2>\r\n");
      out.write("      <p class=\"plan-price\"><img src=\"https://cutt.ly/8LGRT6D\"></p>\r\n");
      out.write("      <ul class=\"plan-features\">\r\n");
      out.write("        <li> <strong> Los usuarios</strong></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      ");
 gestionApp.getUsuarios(); 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     <div class=\"plan\">\r\n");
      out.write("      <h2 class=\"plan-title\">Estadisticas</h2>\r\n");
      out.write("      <p class=\"plan-price\"><img src=\"https://cutt.ly/8LGRT6D\"></p>\r\n");
      out.write("      <ul class=\"plan-features\">\r\n");
      out.write("        <li><strong> De la aplicacion</strong></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      <a href=\"#\" class=\"plan-button\">Ir</a>\r\n");
      out.write("      ");
 gestionApp.getEstadisticas(); 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     <div class=\"plan\">\r\n");
      out.write("      <h2 class=\"plan-title\">Cerrar</h2>\r\n");
      out.write("      <p class=\"plan-price\"><img src=\"https://cutt.ly/8LGRT6D\"></p>\r\n");
      out.write("      <ul class=\"plan-features\">\r\n");
      out.write("        <li><strong>Sesion</strong></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      <a href=\"/index.jsp\" class=\"plan-button\">Ir</a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");




    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
